### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by TheK0tYaRa** [al132mc/alchemistry#103]
```
[04:42:44] [Server thread/ERROR] [FML]: Parsing error loading recipe alchemistry:patchouli_book
com.google.gson.JsonSyntaxException: Unknown item 'patchouli:guide_book'
        at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:214) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$15(CraftingHelper.java:538) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_231]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by Gepett0** [comment]
Are you missing the patchouli mod?
https://www.curseforge.com/minecraft/mc-mods/patchouli

**Comment by ghost** [comment]
There might be a way I can prevent this from showing up even if you don't have patchouli installed, but regardless I just want to be clear that this is not a critical error that will cause a crash; it won't do anything but spam your log..

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
