### ISSUE TITLE
Fission error

### ISSUE THREAD

**Issue by ghost** [al132mc/alchemistry#107]
```
[04:39:03] [Server thread/ERROR] [minecraft/TileEntity]: Failed to load data for block entity alchemistry:fission
java.lang.NullPointerException: null
	at al132.alchemistry.blocks.fission.FissionTile.validateMultiblock(FissionTile.java:148) ~[?:1.14.4-7] {re:classloading}
	at al132.alchemistry.blocks.fission.FissionTile.updateMultiblock(FissionTile.java:131) ~[?:1.14.4-7] {re:classloading}
	at al132.alchemistry.blocks.fission.FissionTile.func_145839_a(FissionTile.java:121) ~[?:1.14.4-7] {re:classloading}
	at net.minecraft.tileentity.TileEntity.lambda$create$1(TileEntity.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_181] {}
	at net.minecraft.tileentity.TileEntity.func_203403_c(TileEntity.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:413) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.storage.ChunkSerializer.lambda$read$2(ChunkSerializer.java:148) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:462) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$24(ChunkManager.java:567) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$25(ChunkManager.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_217353_a(World.java:164) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_212866_a_(World.java:160) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_180495_p(World.java:392) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.canEntityDestroy(ForgeHooks.java:1182) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.BreakBlockGoal.func_75250_a(BreakBlockGoal.java:35) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_181] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:69) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:231) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:684) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) [?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}
[04:39:03] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id alchemistry:fission
[04:39:03] [Server thread/ERROR] [minecraft/TileEntity]: Failed to load data for block entity alchemistry:fusion
java.lang.NullPointerException: null
	at al132.alchemistry.blocks.fusion.FusionTile.validateMultiblock(FusionTile.java:137) ~[?:1.14.4-7] {re:classloading}
	at al132.alchemistry.blocks.fusion.FusionTile.updateMultiblock(FusionTile.java:120) ~[?:1.14.4-7] {re:classloading}
	at al132.alchemistry.blocks.fusion.FusionTile.func_145839_a(FusionTile.java:110) ~[?:1.14.4-7] {re:classloading}
	at net.minecraft.tileentity.TileEntity.lambda$create$1(TileEntity.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_181] {}
	at net.minecraft.tileentity.TileEntity.func_203403_c(TileEntity.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:413) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.storage.ChunkSerializer.lambda$read$2(ChunkSerializer.java:148) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:462) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$24(ChunkManager.java:567) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$25(ChunkManager.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_217353_a(World.java:164) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_212866_a_(World.java:160) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_180495_p(World.java:392) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.canEntityDestroy(ForgeHooks.java:1182) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.BreakBlockGoal.func_75250_a(BreakBlockGoal.java:35) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_181] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:69) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.func_70636_d(ZombieEntity.java:231) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:684) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) [?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}
```

**Comment by ghost** [comment]
I haven't seen any reports of this in quite a while, so I will assume(?) it is fixed. Please create a new issue if you are experiencing this crash.
