### ISSUE TITLE
[Bug]CompactorUI NPE

### ISSUE THREAD

**Issue by XieDeWu** [al132mc/alchemistry#217]
digest:
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "this.currentRecipe" is null
	at com.smashingmods.alchemistry.common.block.compactor.CompactorBlockEntity.lambda$updateRecipe$2(CompactorBlockEntity.java:85) ~[alchemistry-1.18.2-2.0.2.jar%2360!/:1.18.2-2.0.2] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
detail:
[crash-2022-07-24_09.14.49-server.txt](https://github.com/SmashingMods/Alchemistry/files/9174930/crash-2022-07-24_09.14.49-server.txt)

**Comment by Dark-Arcana** [comment]
Same issue as https://github.com/SmashingMods/Alchemistry/issues/214

Fix will be in next release.

**Comment by XieDeWu** [comment]
thank you

> Same issue as #214
> 
> Fix will be in next release.

thank you

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/pull/222
