### ISSUE TITLE
Crash gui dissolver, catalyzer. Crash server 

### ISSUE THREAD

**Issue by roulito** [al132mc/alchemistry#5]
Description: Rendering screen

java.lang.RuntimeException: Slot 1 not in valid range - [0,1)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:210)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:75)
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:202)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at al132.alib.client.ALGuiBase.func_73863_a(ALGuiBase.kt:51)
	at al132.alchemistry.client.GuiBase.func_73863_a(GuiBase.kt:24)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:648)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Gui crash dissolver and catalyzer

Description: Ticking player

java.lang.RuntimeException: Slot 1 not in valid range - [0,1)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:210)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:75)
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:79)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

Crash server pick up catalyzer in my inventory or crash server see gui dissolver, catalyzer

**Comment by al132mc** [comment]
Could you give me more information please? Like what were you doing when you experienced the crash? What mods were you interacting with? As of right now I have no idea how to duplicate either crash.

**Comment by roulito** [comment]
Crash-report client :
https://pastebin.com/PSahTK2c

Crash-report server :
https://pastebin.com/UKuRx4nx

**Comment by al132mc** [comment]
I download the pack and tried to set it up something like this, but I wasn't able to duplicate the crash. I'm not exactly sure how you have your transfer nodes and transfer pipes set up, but I am able to pipe items in and out successfully and open the GUI.

![2018-05-17_12 52 29](https://user-images.githubusercontent.com/39097092/40194786-2f4e3c7c-59d1-11e8-82b4-305153db2f2a.png)
![2018-05-17_12 52 51](https://user-images.githubusercontent.com/39097092/40194787-2f613d5e-59d1-11e8-8f9f-07a45883acad.png)

**Comment by al132mc** [comment]
I tried claiming, chunkloading, relogging, manually inserting, and more, but still no crash. Can you duplicate this crash in single player?

**Comment by roulito** [comment]
No duplicate this crash in single player. Only server

**Comment by roulito** [comment]
By putting new dissolver there is more bug. Conclusion this is due to an accumulation of displacement made of the dissolver with the full inventory with the moving wand which created a buggy dissolver.

**Comment by al132mc** [comment]
I am going to close this issue. If anyone believes this is still a problem they are welcome to open a new issue
